version: '3.8'

services:
  zookeeper:
    image: arm64v8/zookeeper:3.7.0
    platform: linux/arm64
    ports:
      - "2181:2181"

  kafka:
    build: ./kafka
    container_name: kafka-container
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  producer:
    build: ./producer
    depends_on:
      - kafka

  consumer:
    build: ./consumer
    depends_on:
      - kafka

  processor:
    build: ./processor
    depends_on:
      - kafka
